.\"****************************************************************
.\"Copyright (c) 1993 Bell Communications Research, Inc. (Bellcore)
.\"
.\"Permission to use, copy, modify, and distribute this material
.\"for any purpose and without fee is hereby granted, provided
.\"that the above copyright notice and this permission notice
.\"appear in all copies, and that the name of Bellcore not be
.\"used in advertising or publicity pertaining to this
.\"material without the specific, prior written permission
.\"of an authorized representative of Bellcore.  BELLCORE
.\"MAKES NO REPRESENTATIONS ABOUT THE ACCURACY OR SUITABILITY
.\"OF THIS MATERIAL FOR ANY PURPOSE.  IT IS PROVIDED "AS IS",
.\"WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES.
.\"****************************************************************
.\"	$Header: /users/source/archives/atac.vcs/RCS/atacmin.1,v 1.7 1995/12/28 15:10:29 tom Exp $
.\"
.\"$Log: atacmin.1,v $
.\"Revision 1.7  1995/12/28 15:10:29  tom
.\"corrected (missing comment-marker) for log-comments
.\"
.\" Revision 1.6  94/04/05  09:50:15  saul
.\" Add DISTRIBUTION heading.
.\" 
.\" Revision 1.5  94/04/04  10:08:03  jrh
.\" Add Release Copyright
.\" 
.\" Revision 1.4  94/04/04  09:49:05  jrh
.\" Add Release Copyright
.\" 
.\" Revision 1.3  93/10/28  11:58:46  ewk
.\" Change header to indicate release 3.3
.\" 
.\" Revision 1.2  93/07/13  11:22:53  ewk
.\"  Updated SEE ALSO to include atacLD; fixed typos.
.\" 
.\" Revision 1.1  93/04/29  17:01:08  ewk
.\" Initial revision
.\" 
.\"Revision 3.4  93/03/30  14:33:11  saul
.\"Change comments to point to base as point of contact.
.\"
.\"Revision 3.3  93/03/30  08:42:53  saul
.\"Edits from ewk.
.\"
.\"Revision 3.2  93/03/26  10:51:02  saul
.\"Change "construct" to testable attribute.
.\"
.\"Revision 3.1  92/12/30  11:30:39  saul
.\"new
.\"
.\"-----------------------------------------------end of log
.\"
.TH ATACMIN 1 "$Date: 1995/12/28 15:10:29 $" "ATAC release 3.3"
.UC 4
.SH NAME
atacmin \- test set minimization
.SH SYNOPSIS
.B atacmin
[
.B \-hiK
] [
.I other-options
]... [ trace-file ] atac-files...  
.br
.IR other-options :
.br
.in +.5i
.B \-c
test-name
.br
.B \-F
function
.br
.B \-m
{
.B bcdepu
}...
.br
.B \-n
test-name [
.B -x
]
.br
.B \-t
threshold
.in
.SH DESCRIPTION
.I Atacmin
prints the names of a minimal subset of tests
which achieve the same coverage as the whole set of tests.
Tests are recorded in 
.I trace-file.
Coverage is for code in
the source files represented by 
.IR atac-files .
.I Atac-files
are created when a C source file is compiled with
.IR atacCC (1).
The trace file is
produced by executions of a program
compiled with
.IR atacCC (1).
Test names are 
.IR "t.1, t.2, " "..."
by default.
A trace may be renamed using
.IR atactm (1).
If environment variable
.B ATAC_TEST
has a value when a test is run it is used as the test name.
.PP
Various coverage options
may be selected with the 
.B \-m
flag to measure unentered functions or not covered
.IR blocks ,
.IR decisions ,
.IR c-uses ,
or
.IR p-uses .
By default all are included.
If no trace file is specified the value of the
.B ATAC_TRACE
environment variable is used, if set.
Otherwise 
.I  a.out.trace
is used.
If the trace file name is not a complete path and the trace file is
not found in the current directory, the directory named by the
.B ATAC_DIR
environment variable is searched.
.SH OPTIONS
.TP
.BI \-c \ test-name
Minimize based on a comparison of coverage with that of named test cases.
A testable attribute is considered covered only if it is not also covered
by the named test cases.
Wild cards may be used in the test case name.
Wild cards are the same as those used for file names by sh(1) (*, ?, and [...]).
Quote marks may be needed to prevent
the shell from expanding the test name as file names.
Multiple test-cases may also be specified by repeating the
.B \-c
option.
.TP
.BI \-F \ function
Minimize coverage only for C subroutine named
.I function.
Wild cards may be used in the function name (see 
.B \-c
option).
Multiple functions may also be specified by repeating the
.B \-F
option.
.TP
.B \-h
Suppress column headings (used with
.BR  -K ).
.TP
.B \-i
Ignore time stamps on atac files.
By default,
.I atac
issues an error if source files have been modified since
execution of a test represented in the trace file.
.TP
.B \-K
Print a cumulative summary of cost and coverage for minimal set.
.TP
.B \-m \fR{\fB bcdepu \fR}...\fB
Specifies the coverage measures to be used.
.TP
.B \ \ \ \ b
Blocks \- code fragments not containing control flow branching.
.TP
.B  \ \ \ \ c
C-uses \-
(computational uses) pairs of blocks for which
the first block contains an assignment to a variable and
the second block contains a use of that variable in a computation.
.TP
.B  \ \ \ \ d
Decisions \-
pairs of blocks for which
the first block ends at a control flow branch and
the second block is a target of one of these branches.
.TP
.B  \ \ \ \ e
Function entries \- covered when the function is entered at least once.
.TP
.B  \ \ \ \ p
P-uses \-
(predicate uses) triples of blocks for which
the first block contains an assignment to a variable,
the second block ends at a control flow branch
based on a predicate containing that variable, and
the third block is a target of one of these branches.
.TP
.B  \ \ \ \ u
All-uses \-
sum of
.I p-uses
and 
.I c-uses.
.TP
.BI \-n \ test-name
Minimize coverage for named test cases only.
(See also
.B \-x
option.)
Wild cards may be used in the function name (see 
.B \-c
option).
Multiple test-cases may also be specified by repeating the
.B \-n
option.
.TP
.BI \-t \ threshold
Count as covered only testable attributes that executed at least
.I threshold
times.
By default
.I threshold
is 1.
.TP
.B \-x
Exclude test cases specified by
.B \-c
and
.B \-n
options.  Include all unspecified test cases.
.SH EXAMPLE
The following command prints a minimum list of tests 
for program
.I a.out
that achieve the same coverage as all tests run,
where 
.I a.out 
is built using
.I atacCC(1)
to compile
.I src1.c
and 
.I src2.c
and link with
.IR other.o .
.PP
.in +.5i
.nf
.ft CB
atacmin src1.atac src2.atac
.in
.ft
.fi
.SH FILES
\fIfile\fP.atac \- data-flow file.
.br
.IR a.out .trace
\- coverage trace.
.SH "SEE ALSO"
atac(1), atacCC(1), atacLD(1), ataclib(1), atactm(1).
.SH DISTRIBUTION
Copyright (c) 1993 Bell Communications Research, Inc. (Bellcore)
.PP
Permission to use, copy, modify, and distribute this material
for any purpose and without fee is hereby granted, provided
that the above copyright notice and this permission notice
appear in all copies, and that the name of Bellcore not be
used in advertising or publicity pertaining to this
material without the specific, prior written permission
of an authorized representative of Bellcore.  BELLCORE
MAKES NO REPRESENTATIONS ABOUT THE ACCURACY OR SUITABILITY
OF THIS MATERIAL FOR ANY PURPOSE.  IT IS PROVIDED "AS IS",
WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES.
.PP
Send comments or questions to atac@bellcore.com.
